# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/klimt-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter klimtlte klimtltecan klimttd klimtwifi,$(TARGET_DEVICE)),)

endif
